services:
  mssql:
    container_name: mssql_2022
    image: mcr.microsoft.com/mssql/server:2022-latest 
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=A&VeryStrongPassword!@# #userId = SA
      - MSSQL_LOGGING=verbose
      - MSSQL_PID=Developer
    ports:
      - 1433:1433

